from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional, Union

import logging
from datetime import datetime, timezone
import networkx as nx
import numpy as np
import trimesh as tm

from .refine import (
    RefineMode,
    refine_skeleton,
    refine_skeleton_graph,
    resolve_refine_options,
    _resample_polyline_arc_length,
)

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

McfsProfile = Literal["robust", "starlab"]

# Application / CGAL-robust defaults (complex TS-like meshes).
_ROBUST_W_H = 0.5
_ROBUST_W_M = 5.0
# Starlab mcfskel / published CGAL generic defaults (parity harness).
_STARLAB_W_H = 0.1
_STARLAB_W_M = 0.2


def resolve_mcfs_profile(
    profile: McfsProfile | None,
    *,
    w_H: float,
    w_M: float,
    gate_exterior_poles: bool | None,
    quality_speed_tradeoff: float | None = None,
    medially_centered_speed_tradeoff: float | None = None,
) -> tuple[float, float, bool]:
    """Resolve ``(w_H, w_M, gate_exterior_poles)`` from profile + explicit args.

    - ``profile=\"starlab\"`` selects Starlab weights (0.1 / 0.2) and ungated poles
      unless the caller already overrode weights via CGAL aliases or non-robust
      ``w_H`` / ``w_M`` values, or set ``gate_exterior_poles`` explicitly.
    - ``profile=None`` / ``\"robust\"`` uses application defaults (0.5 / 5.0) and
      gated poles (CGAL-style), again unless overridden.
    """
    if profile not in (None, "robust", "starlab"):
        raise ValueError(f"profile must be None, 'robust', or 'starlab'; got {profile!r}")

    if profile == "starlab":
        default_wh, default_wm, default_gate = _STARLAB_W_H, _STARLAB_W_M, False
    else:
        default_wh, default_wm, default_gate = _ROBUST_W_H, _ROBUST_W_M, True

    if quality_speed_tradeoff is not None:
        wh = float(quality_speed_tradeoff)
    elif profile == "starlab" and float(w_H) == _ROBUST_W_H:
        # Function signature default is robust; remap when requesting starlab profile.
        wh = float(default_wh)
    else:
        wh = float(w_H)

    if medially_centered_speed_tradeoff is not None:
        wm = float(medially_centered_speed_tradeoff)
    elif profile == "starlab" and float(w_M) == _ROBUST_W_M:
        wm = float(default_wm)
    else:
        wm = float(w_M)

    gate = default_gate if gate_exterior_poles is None else bool(gate_exterior_poles)
    return wh, wm, gate


@dataclass
class Skeleton:
    """1D curve skeleton extracted from a contracted meso-skeleton surface.

    Attributes
    ----------
    nodes : (k, 3) float ndarray
        Node positions in 3D.
    edges : (e, 2) int ndarray
        Undirected edges as pairs of indices into ``nodes``.
    graph : networkx.Graph
        Same connectivity with node attribute ``pos`` and edge ``weight``.
    """

    nodes: np.ndarray
    edges: np.ndarray
    graph: nx.Graph

    def write_swc(
        self,
        filepath: str,
        *,
        node_type: int = 0,
        default_radius: float = 1.0,
        break_cycles: str = "mst",
        annotate: bool = True,
    ) -> None:
        """Write the skeleton to an SWC file.

        SWC rows: n T x y z R P
        - n: 1-based node id
        - T: node type (default 0=undefined)
        - x y z: coordinates
        - R: radius (use default unless application provides per-node radii)
        - P: parent id (-1 for root)

        If the skeleton graph has cycles, we build a spanning forest (default MST)
        and annotate in the header which edges were removed to break cycles.
        """
        G = self.graph.copy()
        # Ensure positions exist for all nodes
        for n in G.nodes:
            if "pos" not in G.nodes[n]:
                G.nodes[n]["pos"] = np.asarray(self.nodes[n], dtype=float)

        # Spanning forest and list of removed edges
        if break_cycles == "mst":
            forest, removed = _spanning_forest_by_mst(G)
        elif break_cycles == "bfs":
            forest, removed = _spanning_forest_by_bfs(G)
        else:
            # default fallback
            forest, removed = _spanning_forest_by_mst(G)

        # Build SWC order per connected component so parents precede children
        order, parent_of = _swc_bfs_order(forest)

        # Write file
        with open(filepath, "w", encoding="utf-8") as f:
            # Header
            ts = datetime.now(timezone.utc).isoformat()
            f.write(f"# SWC generated by pymcfs on {ts}\n")
            if annotate and removed:
                f.write(f"# cycles_broken: {len(removed)}\n")
                for (u, v) in removed:
                    f.write(f"# removed_edge {u} {v}\n")
            f.write("# Columns: n T x y z R P\n")

            # Map original node to SWC id
            swc_id: dict[int, int] = {}
            next_id = 1
            for n in order:
                swc_id[n] = next_id
                next_id += 1

            # Emit rows
            for n in order:
                x, y, z = map(float, G.nodes[n]["pos"])  # type: ignore[index]
                pid = parent_of.get(n, None)
                p_swc = -1 if pid is None else swc_id[pid]
                f.write(f"{swc_id[n]} {int(node_type)} {x:.6f} {y:.6f} {z:.6f} {float(default_radius):.6f} {p_swc}\n")

    def to_polylines(self) -> list[np.ndarray]:
        """Split the skeleton into polylines at junctions (degree ≠ 2).

        Returns
        -------
        list of (k_i, 3) float arrays
            Each array is an ordered sequence of 3D points along one maximal path
            between junctions/leaves (polyline decomposition).
        """
        G = self.graph
        if G.number_of_nodes() == 0:
            return []
        for n in G.nodes:
            if "pos" not in G.nodes[n]:
                # fall back to nodes array if densely indexed
                try:
                    G.nodes[n]["pos"] = np.asarray(self.nodes[int(n)], dtype=float)
                except Exception:
                    pass

        deg = dict(G.degree())
        terminals = {n for n, d in deg.items() if d != 2}
        if not terminals:
            # Pure cycle: emit one closed loop starting at an arbitrary node
            start = next(iter(G.nodes))
            cycle = nx.find_cycle(G, source=start)
            pts = [np.asarray(G.nodes[u]["pos"], dtype=float) for u, v in cycle]
            pts.append(np.asarray(G.nodes[cycle[0][0]]["pos"], dtype=float))
            return [np.vstack(pts)]

        polylines: list[np.ndarray] = []
        visited: set[tuple[int, int]] = set()

        def edge_key(a: int, b: int) -> tuple[int, int]:
            return (a, b) if a < b else (b, a)

        for t in terminals:
            for nbr in G.neighbors(t):
                ek = edge_key(t, nbr)
                if ek in visited:
                    continue
                path = [t, nbr]
                visited.add(ek)
                prev, curr = t, nbr
                while deg.get(curr, 0) == 2:
                    nxts = [x for x in G.neighbors(curr) if x != prev]
                    if not nxts:
                        break
                    nxt = nxts[0]
                    visited.add(edge_key(curr, nxt))
                    path.append(nxt)
                    prev, curr = curr, nxt
                pts = np.array([G.nodes[n]["pos"] for n in path], dtype=float)
                polylines.append(pts)
        return polylines

    def write_polylines(self, filepath: str) -> None:
        """Write polylines as text: ``N x y z x y z ...`` per line."""
        with open(filepath, "w", encoding="utf-8") as f:
            for pl in self.to_polylines():
                coords = " ".join(f"{float(c):.9g}" for p in pl for c in p)
                f.write(f"{pl.shape[0]} {coords}\n")

    def write_cg(self, filepath: str) -> None:
        """Write the skeleton as a Starlab Curve Graph (``.cg``) file."""
        from .cg_io import write_cg

        write_cg(filepath, self.nodes, self.edges)

    def plot_3d(
        self,
        mesh: tm.Trimesh | tuple[np.ndarray, np.ndarray] | None = None,
        *,
        show_nodes: bool = False,
        node_size: float = 4.0,
        node_color: str = "#d62728",
        edge_color: str = "#1f77b4",
        edge_width: float = 4.0,
        mesh_color: str = "#AAAAAA",
        mesh_opacity: float = 0.3,
        title: str | None = None,
        autoshow: bool = True,
    ) -> object:
        """Interactive 3D visualization of the skeleton with optional mesh overlay.

        Parameters
        ----------
        mesh : trimesh.Trimesh or (V,F) or None
            If provided, overlays the original mesh using Plotly Mesh3d. You can pass
            either a trimesh.Trimesh instance or a tuple (vertices, faces).
        show_nodes : bool
            If True, also draw node markers in addition to skeleton edges.
        node_size : float
            Marker size for nodes when show_nodes=True.
        node_color : str
            Color for node markers.
        edge_color : str
            Color for skeleton edges.
        edge_width : float
            Line width for skeleton edges.
        mesh_color : str
            Color for mesh surface.
        mesh_opacity : float
            Opacity for mesh surface in [0,1].
        title : str or None
            Figure title.
        autoshow : bool
            If True, call fig.show() before returning (useful in notebooks).

        Returns
        -------
        plotly.graph_objects.Figure
            The created Plotly figure.
        """
        import plotly.graph_objects as go

        traces: list[go.BaseTraceType] = []

        # Optional mesh overlay
        if mesh is not None:
            if isinstance(mesh, tm.Trimesh):
                V = np.asarray(mesh.vertices, dtype=float)
                F = np.asarray(mesh.faces, dtype=int)
            else:
                try:
                    V, F = mesh  # type: ignore[misc]
                    V = np.asarray(V, dtype=float)
                    F = np.asarray(F, dtype=int)
                except Exception:
                    raise TypeError("mesh must be a trimesh.Trimesh or a (V,F) tuple")
            if V.size > 0 and F.size > 0:
                mesh_trace = go.Mesh3d(
                    x=V[:, 0], y=V[:, 1], z=V[:, 2],
                    i=F[:, 0], j=F[:, 1], k=F[:, 2],
                    color=mesh_color,
                    opacity=float(np.clip(mesh_opacity, 0.0, 1.0)),
                    name="mesh",
                    flatshading=True,
                    lighting=dict(ambient=0.6, diffuse=0.7, roughness=0.9),
                    showscale=False,
                )
                traces.append(mesh_trace)

        # Skeleton edges as line segments
        P = np.asarray(self.nodes, dtype=float)
        E = np.asarray(self.edges, dtype=int)
        if P.size > 0 and E.size > 0:
            xs: list[float | None] = []
            ys: list[float | None] = []
            zs: list[float | None] = []
            for (a, b) in E:
                pa = P[int(a)]
                pb = P[int(b)]
                xs.extend([float(pa[0]), float(pb[0]), None])
                ys.extend([float(pa[1]), float(pb[1]), None])
                zs.extend([float(pa[2]), float(pb[2]), None])
            edge_trace = go.Scatter3d(
                x=xs, y=ys, z=zs,
                mode="lines",
                line=dict(color=edge_color, width=float(edge_width)),
                name="skeleton",
            )
            traces.append(edge_trace)

        # Optional node markers
        if show_nodes and P.size > 0:
            node_trace = go.Scatter3d(
                x=P[:, 0], y=P[:, 1], z=P[:, 2],
                mode="markers",
                marker=dict(size=float(node_size), color=node_color),
                name="nodes",
            )
            traces.append(node_trace)

        fig = go.Figure(data=traces)
        fig.update_layout(
            title=title or "Skeleton 3D",
            scene=dict(
                xaxis=dict(visible=True),
                yaxis=dict(visible=True),
                zaxis=dict(visible=True),
                aspectmode="data",
            ),
            legend=dict(orientation="h", yanchor="bottom", y=1.02),
            margin=dict(l=0, r=0, t=40, b=0),
        )

        if autoshow:
            fig.show()
        return fig

    def refine(
        self,
        *,
        mode: RefineMode = "uniform",
        spacing: float | None = None,
        spacing_frac: float | None = None,
    ) -> "Skeleton":
        """Return a copy with optional chain merge / arc-length resampling.

        See :func:`refine_skeleton`.
        """
        return refine_skeleton(
            self, mode=mode, spacing=spacing, spacing_frac=spacing_frac
        )


def _spanning_forest_by_mst(G: nx.Graph) -> tuple[nx.Graph, list[tuple[int, int]]]:
    H = nx.Graph()
    H.add_nodes_from(G.nodes(data=True))
    removed: list[tuple[int, int]] = []
    for comp in nx.connected_components(G):
        sub = G.subgraph(comp).copy()
        # Ensure weights on edges
        for u, v, d in sub.edges(data=True):
            if "weight" not in d:
                try:
                    pu = np.asarray(sub.nodes[u]["pos"], dtype=float)
                    pv = np.asarray(sub.nodes[v]["pos"], dtype=float)
                    d["weight"] = float(np.linalg.norm(pu - pv))
                except Exception:
                    d["weight"] = 1.0
        if sub.number_of_edges() == 0:
            H = nx.compose(H, sub)
            continue
        T = nx.minimum_spanning_tree(sub, weight="weight")
        H = nx.compose(H, T)
        # Edges removed to break cycles
        for (u, v) in sub.edges():
            if not T.has_edge(u, v):
                removed.append((u, v))
    return H, removed


def _spanning_forest_by_bfs(G: nx.Graph) -> tuple[nx.Graph, list[tuple[int, int]]]:
    H = nx.Graph()
    H.add_nodes_from(G.nodes(data=True))
    removed: list[tuple[int, int]] = []
    for comp in nx.connected_components(G):
        nodes = list(comp)
        if not nodes:
            continue
        root = nodes[0]
        Tdir = nx.bfs_tree(G.subgraph(comp), source=root)
        T = nx.Graph()
        T.add_nodes_from(Tdir.nodes(data=True))
        T.add_edges_from(Tdir.edges())
        H = nx.compose(H, T)
        # removed
        sub = G.subgraph(comp)
        for e in sub.edges():
            if not T.has_edge(*e):
                removed.append(e)
    return H, removed


def _swc_bfs_order(G: nx.Graph) -> tuple[list[int], dict[int, int | None]]:
    order: list[int] = []
    parent: dict[int, int | None] = {}
    visited: set[int] = set()
    for comp in nx.connected_components(G):
        comp_nodes = list(comp)
        if not comp_nodes:
            continue
        # Prefer a degree-1 leaf as root if available
        leaves = [n for n in comp_nodes if G.degree(n) <= 1]
        root = leaves[0] if leaves else comp_nodes[0]
        queue = [root]
        visited.add(root)
        parent[root] = None
        while queue:
            u = queue.pop(0)
            order.append(u)
            for v in G.neighbors(u):
                if v in visited:
                    continue
                visited.add(v)
                parent[v] = u
                queue.append(v)
    return order, parent


def _coerce_mesh(mesh: Union[tm.Trimesh, object]) -> tm.Trimesh:
    """Accept ``trimesh.Trimesh`` or ``MeshManager``; raise ``TypeError`` otherwise."""
    if isinstance(mesh, tm.Trimesh):
        return mesh
    try:
        from .mesh import MeshManager
    except Exception:
        MeshManager = None  # type: ignore
    if MeshManager is not None and isinstance(mesh, MeshManager):  # type: ignore
        return mesh.to_trimesh()  # type: ignore[return-value]
    raise TypeError("mesh must be a trimesh.Trimesh or MeshManager")


def skeletonize(
    mesh: Union[tm.Trimesh, object],
    *,
    w_H: float = 0.5,
    w_M: float = 5.0,
    quality_speed_tradeoff: float | None = None,
    medially_centered_speed_tradeoff: float | None = None,
    gate_exterior_poles: bool | None = None,
    profile: McfsProfile | None = None,
    max_iterations: int = 500,
    timeout_seconds: float | None = 120.0,
    min_edge_length: float | None = None,
    max_triangle_angle: float = 110.0,
    area_variation_factor: float = 1e-4,
    keep_largest_component: bool = False,
    refine: bool | RefineMode = False,
    refine_spacing: float | None = None,
    refine_spacing_frac: float | None = None,
    compress_chains: bool = False,
    resample_spacing: float | None = None,
    validate: bool = True,
    verbose: bool = False,
    log: Optional[logging.Logger] = None,
) -> Skeleton:
    """Mean-curvature-flow skeletonization of a closed triangle mesh.

    Parameters
    ----------
    mesh :
        Input closed triangle mesh (``trimesh.Trimesh`` or ``MeshManager``).
    w_H, quality_speed_tradeoff :
        Quality/speed tradeoff (default 0.5). Alias: ``quality_speed_tradeoff``.
    w_M, medially_centered_speed_tradeoff :
        Medial-centering tradeoff (default 5.0). Alias:
        ``medially_centered_speed_tradeoff``. Used whenever ``w_M > 0``.
    gate_exterior_poles :
        If True, apply ``w_M`` only for poles inside the mesh (CGAL-style).
        Default True for robust profile; False for ``profile=\"starlab\"``.
    profile :
        ``None`` / ``\"robust\"`` — gated poles, defaults ``w_H=0.5``, ``w_M=5``.
        ``\"starlab\"`` — ungated poles, ``w_H=0.1``, ``w_M=0.2`` (parity dumps).
    max_iterations, timeout_seconds :
        Contraction stop limits.
    min_edge_length, max_triangle_angle :
        Remesh thresholds during contraction.
    area_variation_factor :
        Relative area change for convergence (vs initial surface area).
    keep_largest_component :
        If True, keep only the largest connected component of the curve graph.
    refine, refine_spacing, refine_spacing_frac :
        Optional post-conversion curve refinement (off by default).
        ``refine=True`` / ``\"uniform\"`` arc-length resamples chains;
        ``refine=\"compress\"`` keeps only junctions/leaves.
    compress_chains, resample_spacing :
        Legacy aliases for refine when ``refine`` is left False.
    validate :
        Run mesh validation before contraction.
    verbose, log :
        Progress logging.

    Returns
    -------
    Skeleton
        Curve skeleton with ``nodes``, ``edges``, and ``graph``.

    Raises
    ------
    TypeError
        If ``mesh`` is not a Trimesh or MeshManager.
    """
    _log = log or logger
    m = _coerce_mesh(mesh)

    wh, wm, gate = resolve_mcfs_profile(
        profile,
        w_H=w_H,
        w_M=w_M,
        gate_exterior_poles=gate_exterior_poles,
        quality_speed_tradeoff=quality_speed_tradeoff,
        medially_centered_speed_tradeoff=medially_centered_speed_tradeoff,
    )

    from .mcfs import MeanCurvatureFlowSkeletonization

    driver = MeanCurvatureFlowSkeletonization(
        m,
        w_H=wh,
        w_M=wm,
        gate_exterior_poles=gate,
        min_edge_length=min_edge_length,
        max_triangle_angle=float(max_triangle_angle),
        area_variation_factor=float(area_variation_factor),
        max_iterations=int(max_iterations),
        timeout_seconds=timeout_seconds,
        validate=bool(validate),
        verbose=verbose,
        log=_log,
    )
    if verbose:
        _log.info(
            "Skeleton: MCFS (max_iters=%d, w_H=%.3g, w_M=%.3g, gate_poles=%s, profile=%s)",
            max_iterations,
            wh,
            wm,
            gate,
            profile,
        )
    driver.contract_until_convergence()
    return driver.convert_to_skeleton(
        refine=refine,
        refine_spacing=refine_spacing,
        refine_spacing_frac=refine_spacing_frac,
        compress_chains=bool(compress_chains),
        resample_spacing=resample_spacing,
        keep_largest_component=bool(keep_largest_component),
    )


def thin_mesh(
    mesh: Union[tm.Trimesh, object],
    *,
    w_H: float = 0.5,
    w_M: float = 5.0,
    quality_speed_tradeoff: float | None = None,
    medially_centered_speed_tradeoff: float | None = None,
    gate_exterior_poles: bool | None = None,
    profile: McfsProfile | None = None,
    max_iterations: int = 500,
    timeout_seconds: float | None = 120.0,
    min_edge_length: float | None = None,
    max_triangle_angle: float = 110.0,
    area_variation_factor: float = 1e-4,
    validate: bool = True,
    verbose: bool = False,
    log: Optional[logging.Logger] = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Contract a mesh with MCFS; return the meso-skeleton surface ``(V, F)``.

    Parameters match :func:`skeletonize` contraction controls (no curve-graph
    conversion). CGAL-style aliases ``quality_speed_tradeoff`` /
    ``medially_centered_speed_tradeoff`` are accepted.

    Returns
    -------
    V : (n, 3) float ndarray
    F : (m, 3) int ndarray

    Raises
    ------
    TypeError
        If ``mesh`` is not a Trimesh or MeshManager.
    """
    _log = log or logger
    m = _coerce_mesh(mesh)

    wh, wm, gate = resolve_mcfs_profile(
        profile,
        w_H=w_H,
        w_M=w_M,
        gate_exterior_poles=gate_exterior_poles,
        quality_speed_tradeoff=quality_speed_tradeoff,
        medially_centered_speed_tradeoff=medially_centered_speed_tradeoff,
    )

    from .mcfs import MeanCurvatureFlowSkeletonization

    driver = MeanCurvatureFlowSkeletonization(
        m,
        w_H=wh,
        w_M=wm,
        gate_exterior_poles=gate,
        min_edge_length=min_edge_length,
        max_triangle_angle=float(max_triangle_angle),
        area_variation_factor=float(area_variation_factor),
        max_iterations=int(max_iterations),
        timeout_seconds=timeout_seconds,
        validate=bool(validate),
        verbose=verbose,
        log=_log,
    )
    driver.contract_until_convergence()
    return driver.V.copy(), driver.F.copy()


def curve_skeleton_from_mesh(
    V: np.ndarray,
    F: np.ndarray,
    *,
    refine: bool | RefineMode = False,
    refine_spacing: float | None = None,
    refine_spacing_frac: float | None = None,
    compress_chains: bool = False,
    resample_spacing: float | None = None,
    keep_largest_component: bool = False,
) -> Skeleton:
    """Convert a triangle mesh surface to a 1D curve-graph :class:`Skeleton`.

    Parameters
    ----------
    V : (n, 3) float
        Vertex positions (typically a meso-skeleton from :func:`thin_mesh`).
    F : (m, 3) int
        Triangle indices.
    refine, refine_spacing, refine_spacing_frac, compress_chains, resample_spacing :
        Same meaning as in :func:`skeletonize`.
    keep_largest_component :
        If True, keep only the largest connected component.

    Returns
    -------
    Skeleton
    """
    from .mcfs import meso_surface_to_curve_graph

    G = meso_surface_to_curve_graph(V, F)
    if keep_largest_component and G.number_of_nodes() > 0:
        comps = list(nx.connected_components(G))
        if len(comps) > 1:
            G = G.subgraph(max(comps, key=len)).copy()
    mode, spacing, spacing_frac = resolve_refine_options(
        refine=refine,
        refine_spacing=refine_spacing,
        refine_spacing_frac=refine_spacing_frac,
        compress_chains=compress_chains,
        resample_spacing=resample_spacing,
    )
    if mode is not None:
        G = refine_skeleton_graph(
            G, mode=mode, spacing=spacing, spacing_frac=spacing_frac
        )
    mapping = {n: i for i, n in enumerate(G.nodes)}
    if mapping:
        G = nx.relabel_nodes(G, mapping, copy=True)
    nodes_arr = (
        np.array([G.nodes[n]["pos"] for n in G.nodes], dtype=float)
        if G.number_of_nodes()
        else np.zeros((0, 3))
    )
    edges_arr = (
        np.array([[u, v] for u, v in G.edges], dtype=int)
        if G.number_of_edges()
        else np.zeros((0, 2), dtype=int)
    )
    return Skeleton(nodes=nodes_arr, edges=edges_arr, graph=G)


# Re-export refine API for stable ``from pymcfs.skeleton import …``
__all__ = [
    "Skeleton",
    "skeletonize",
    "thin_mesh",
    "curve_skeleton_from_mesh",
    "refine_skeleton",
    "refine_skeleton_graph",
    "resolve_refine_options",
    "resolve_mcfs_profile",
    "RefineMode",
    "McfsProfile",
    "_resample_polyline_arc_length",
]
